SELECT 
	PL.PL,
	SYS.SYS,
	PL.Equipment_No,
	DI.DI,
	MODULE.MODULE,
	ISSUEDBY.Description as [Issued By], 
	PL.Act_By,
	PL.Vendor_Name,
	PL.Description,
	PL.Engineering_req,
	PL.Req_Material,
	ApprovedBy.Description as [Approved By],
	CarriedBY.Description as [Cleared By],
	CheckedBY.Description as [Checked By],
	PL.CorrectiveAction,
	CASE WHEN PL.TA_Id IS NOT NULL THEN TA.TA ELSE CASE WHEN PL.OT_Id IS NOT NULL THEN OT.OT END END AS TA,
	PL.Drawing_No,
	TAL.TAL,
	PL.ExtraData1,
	PL.ExtraData2,
	PL.ExtraData3,
	SUBSYSTEMPROGRESSPart2.OTStatus,
	CASE WHEN PL.TA_Id IS NOT NULL THEN TA.Description ELSE CASE WHEN PL.OT_Id IS NOT NULL THEN OT.Description END END AS [TA Description],
	PLP.PLP,
	PLAY.PLAY,
	PL.Issue_Date,
	PL.Third_Date,	
	PL.Clearance_Date,	
	PL.Approve_Date,
	CASE WHEN SUBSYSTEMPROGRESS.PCTaskQty IS NULL OR SUBSYSTEMPROGRESS.PCTaskQty=0.0 THEN 0.0 ELSE 100.0*(SUBSYSTEMPROGRESS.PCTaskDoneQty/SUBSYSTEMPROGRESS.PCTaskQty) END as PC,
	CASE WHEN SUBSYSTEMPROGRESS.CTaskMhrs IS NULL AND SUBSYSTEMPROGRESSPart2.CPart2TaskMhrs IS NULL THEN 0.0 ELSE	CASE  WHEN SUBSYSTEMPROGRESS.CTaskMhrs IS NOT NULL AND SUBSYSTEMPROGRESSPart2.CPart2TaskMhrs IS NOT NULL AND SUBSYSTEMPROGRESS.CTaskMhrs+SUBSYSTEMPROGRESSPart2.CPart2TaskMhrs != 0	THEN 100.0*(SUBSYSTEMPROGRESS.CTaskDoneMhrs+SUBSYSTEMPROGRESSPart2.CPart2DoneMhrs)/(SUBSYSTEMPROGRESS.CTaskMhrs+SUBSYSTEMPROGRESSPart2.CPart2TaskMhrs) 
																																																								ELSE	CASE WHEN SUBSYSTEMPROGRESS.CTaskMhrs IS NOT NULL AND SUBSYSTEMPROGRESS.CTaskMhrs !=0 THEN 100.0*(SUBSYSTEMPROGRESS.CTaskDoneMhrs)/(SUBSYSTEMPROGRESS.CTaskMhrs) ELSE	CASE WHEN SUBSYSTEMPROGRESSPart2.CPart2TaskMhrs!=0 THEN 100.0*(SUBSYSTEMPROGRESSPart2.CPart2DoneMhrs)/(SUBSYSTEMPROGRESSPart2.CPart2TaskMhrs) END 
																																																										END 
																													END 
	END as C,
	CASE WHEN	PL.Approve_Date IS NULL 
		AND		SUBSYSTEMPROGRESSPart2.CPart2OTPTaskMhrs <> 0 
		AND		(SUBSYSTEMPROGRESS.CTaskMhrs - SUBSYSTEMPROGRESS.CTaskDoneMhrs) = 0 
		AND		((SUBSYSTEMPROGRESSPart2.CPart2TaskMhrs+SUBSYSTEMPROGRESS.CTaskMhrs)-SUBSYSTEMPROGRESSPart2.CPart2OTPTaskMhrs)-((SUBSYSTEMPROGRESSPart2.CPart2DoneMhrs+SUBSYSTEMPROGRESS.CTaskDoneMhrs)-SUBSYSTEMPROGRESSPart2.CPart2OTPDoneMhrs) = 0
		AND		SUBSYSTEMPROGRESSPart2.CPart2OTPTaskMhrs - SUBSYSTEMPROGRESSPart2.CPart2OTPDoneMhrs <> 0
		THEN 'TRUE' 
		ELSE 'FALSE' 
	END AS [ONLY OT REMAINING]	
FROM PL INNER JOIN 
		(	SELECT PLAR_Id, PLAR.Description 
		FROM PLAR
		)	as ISSUEDBY ON ISSUEDBY.PLAR_Id=PL.Issued_by_Id
		LEFT JOIN
		(	SELECT PLAR_Id, PLAR.Description 
		FROM PLAR
		) as CarriedBY on CarriedBY.PLAR_Id=PL.Cleared_By_Id
		LEFT JOIN
		(	SELECT PLAR_Id, PLAR.Description 
		FROM PLAR
		) as CheckedBY on CheckedBY.PLAR_Id=PL.Checked_By_Id
		LEFT JOIN
		( SELECT PLAR_Id, PLAR.Description 
		FROM PLAR
		) as ApprovedBy on ApprovedBy.PLAR_Id=PL.Third_By_id
		INNER JOIN SYS ON SYS.SYS_Id=PL.SYS_Id
		LEFT JOIN
		(	SELECT	dbo.TA.SYS_Id, 
			SUM(CASE WHEN TAA = 'CCK' OR TAA = 'STS' OR TAA = 'PIP' THEN 1 ELSE 0 END) AS PCTaskQty, 
			SUM(CASE WHEN (TAA = 'CCK' OR TAA = 'STS' OR TAA = 'PIP') AND Completion_Date IS NOT NULL THEN 1 ELSE 0 END) AS PCTaskDoneQty,
			SUM(CASE WHEN (TAA = 'FTS' OR TAA = 'PRC') THEN Estimated_Man_Hours ELSE 0 END)AS CTaskMhrs, 
			SUM(CASE WHEN (TAA = 'FTS' OR TAA = 'PRC') AND Completion_Date IS NOT NULL THEN Estimated_Man_Hours ELSE 0 END) AS CTaskDoneMhrs
			FROM TA INNER JOIN TAA ON TA.TAA_ID=TAA.TAA_Id
			WHERE TA.Rev_Code='R'
			GROUP BY TA.SYS_Id
		) as SUBSYSTEMPROGRESS ON SUBSYSTEMPROGRESS.SYS_Id=PL.SYS_Id
		LEFT JOIN
		(	select dbo.OT.SYS_Id,
			CONVERT(varchar,SUM(CASE WHEN TAA='OTS' AND OT.Completion_Date IS NOT NULL THEN 1 ELSE 0 END)) + '/' + CONVERT(varchar,SUM(CASE WHEN TAA='OTS' THEN 1 ELSE 0 END)) as OTStatus,
			SUM(OT.Estimated_Man_Hours) as CPart2TaskMhrs,
			SUM(CASE WHEN Completion_Date IS NOT NULL THEN Estimated_Man_Hours ELSE 0 END) as CPart2DoneMhrs,
			SUM(CASE WHEN TAA='OTS' THEN OT.Estimated_Man_Hours END) as CPart2OTPTaskMhrs,
			SUM(CASE WHEN TAA='OTS' AND Completion_Date IS NOT NULL THEN Estimated_Man_Hours ELSE 0 END) as CPart2OTPDoneMhrs
			FROM OT INNER JOIN TAA ON OT.TAA_ID=TAA.TAA_Id
			WHERE OT.Rev_Code='R'	
			GROUP BY OT.SYS_Id	
		) as SUBSYSTEMPROGRESSPart2 ON SUBSYSTEMPROGRESSPart2.SYS_Id=PL.SYS_Id
		INNER JOIN PLP on PL.PLP_Id=PLP.PLP_Id
		INNER JOIN DI ON DI.DI_Id=PL.DI_Id
		LEFT JOIN MODULE ON PL.MODULE_ID=MODULE.MODULE_ID
		LEFT JOIN TAL ON PL.TAL_Id=TAL.TAL_Id
		LEFT JOIN TA ON TA.TA_Id=PL.TA_Id
		LEFT JOIN OT ON OT.OT_Id=PL.OT_Id
		LEFT JOIN IT ON PL.IT_Id=IT.IT_Id
		LEFT JOIN PLAY ON PLAY.PLAY_Id=PL.PLAY_Id
WHERE PL.Rev_Code='R' AND PL.PL <> '-'
